### PR TITLE
update to 1ed76ea

### PR DESCRIPTION
**Pull request by daltonbohning**
Now that daos handles compatibility issues with mpifileutils, this can be
updated to 1ed76ea, which is not backwards compatible.

Signed-off-by: Dalton Bohning <daltonx.bohning@intel.com>

### CODE REVIEW

**Comment by daltonbohning** [comment]
Step 1: daos PR to verify mpifileutils works with the current mpifileutils in CI:
https://github.com/daos-stack/daos/pull/4126

**Comment by daltonbohning** [comment]
daos-stack/daos#4126 contains compatibility changes that will allow daos functional tests to work with the current mpifileutils in CI, and with this updated mpifileutils.

Step 1: Run compatibility changes against current version of mpifileutils in CI.
All datamover tests completed successfully:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-4126/3/tests

Step 2: Run compatibility changes against this updated version of mpifileutils in CI.
**_Pending_**
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-4126/6/pipeline

**Comment by daltonbohning** [comment]
@brianjmurrell daos-stack/daos#4126 successfully ran all datamover tests with the current mpifileutils rpm and this updated mpifileutils rpm (see comment above).
I think we should be good to land daos-stack/daos#4126 first (it adds the backwards compatibility), and then land this updated mpifileutils (which has been shown to work).

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
You will want to `git rm 0.10.1...4ec7841.patch` in this PR also.

**Comment by daltonbohning** [comment]
> You will want to `git rm 0.10.1...4ec7841.patch` in this PR also.

In that case, do we want to remove all old patch files?
```
git rm 0.10.1...4ec7841.patch
git rm 397.patch
git rm v0.10.1...871d8f7.patch
```

Also, if possible, I'd like to avoid re-running https://github.com/daos-stack/daos/pull/4126 again against the updated package, if possible, since https://github.com/daos-stack/daos/pull/4126 is _**just about**_ approved to be merged.

There will be another PR to bump the version from `0` to `1`, and then there are also some other more recent changes in the mpifileutils upstream that will require another package update as well. Are you okay with the old patch file(s) being remove at that time? (I can create a PR now to remove them, so we don't forget)

**Comment by brianjmurrell** [comment]
> In that case, do we want to remove all old patch files?
> 
> ```
> git rm 0.10.1...4ec7841.patch
> git rm 397.patch
> git rm v0.10.1...871d8f7.patch
> ```

Yeah, if they are not being used, nuke 'em.

> Also, if possible, I'd like to avoid re-running [daos-stack/daos#4126](https://github.com/daos-stack/daos/pull/4126) again against the updated package,

I think that's reasonable given that this is a cleanup that doesn't affect the content of the resulting package in any way.

> There will be another PR to bump the version from `0` to `1`,

Version of what?  mpifileutils?  It's going to have an official upstream release of 1.x made soon?

> and then there are also some other more recent changes in the mpifileutils upstream that will require another package update as well. Are you okay with the old patch file(s) being remove at that time? (I can create a PR now to remove them, so we don't forget)

Let's just remove them all in this PR since we know that it's immaterial to the final result.  In any case, this PR doesn't block daos-stack/daos#4126 in any way, no matter what, since that PR is to simply introduce the backward compatibility for when a future mpifileutils breaks the interface, right?

**Comment by daltonbohning** [comment]
> > There will be another PR to bump the version from `0` to `1`,
> 
> Version of what? mpifileutils? It's going to have an official upstream release of 1.x made soon?

I should have been clear. I was referring to the DAOS major version that Ken is working on, which changes:
`mpifileutils-mpich-daos-0` to `mpifileutils-mpich-daos-1`
Ken has #7 for this, but it would need to be rebased on top of this PR. I've actually already put together a branch for this.
(As a side note, mpifileutils does plan to have a ?minor? version update within the next few months)

> ... In any case, this PR doesn't block [daos-stack/daos#4126](https://github.com/daos-stack/daos/pull/4126) in any way, no matter what, since that PR is to simply introduce the backward compatibility for when a future mpifileutils breaks the interface, right?

Right, it's actually the other way around. [daos-stack/daos#4126](https://github.com/daos-stack/daos/pull/4126) blocks _**THIS**_ PR, since we can't update the package until compatibility checks are in place.
Step 1: Merge [daos-stack/daos#4126](https://github.com/daos-stack/daos/pull/4126)
Step 2: Merge _**THIS**_ PR
Step 3: Merge either #7 rebased, or [this branch](https://github.com/daos-stack/mpifileutils-pkg/tree/dbohninx-update-version)

**Comment by daltonbohning** [comment]
> Let's just remove them all in this PR since we know that it's immaterial to the final result.

Just to be clear... We should remove the other patches in _**THIS**_ PR, but we don't have to re-run  daos-stack/daos#4126 ?

**Comment by brianjmurrell** [comment]
> > Let's just remove them all in this PR since we know that it's immaterial to the final result.
> 
> Just to be clear... We should remove the other patches in _**THIS**_ PR, but we don't have to re-run [daos-stack/daos#4126](https://github.com/daos-stack/daos/pull/4126) ?

Right.  Removing those patches doesn't affect the built product here.  It's just a repo tidy up operation that is at least partially required by this PR to remove the patch being replaced.

**Comment by brianjmurrell** [comment]
> Step 1: Merge [daos-stack/daos#4126](https://github.com/daos-stack/daos/pull/4126)

Roger.

> Step 2: Merge _**THIS**_ PR

Does this unblock @kccain in that he can stop having to add `-datamover` to his test tags?  He needs that to get his PR landed.

**Comment by daltonbohning** [comment]
> > Step 1: Merge [daos-stack/daos#4126](https://github.com/daos-stack/daos/pull/4126)
> 
> Roger.
> 
> > Step 2: Merge _**THIS**_ PR
> 
> Does this unblock @kccain in that he can stop having to add `-datamover` to his test tags? He needs that to get his PR landed.

Yes, this would unblock that work. [daos-stack/daos#4126](https://github.com/daos-stack/daos/pull/4126) is just waiting for gatekeeper. I'll ping them today to see about getting it merged, so that we can merge this PR.

**Comment by daltonbohning** [comment]
STATUS

Step 1: Compatibility PR to allow daos functional tests to work with the current mpifileutils in CI, and with this updated mpifileutils.
_**DONE**_
Datamover tests against current version in CI:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-4126/3/tests
Datamover tests against _**THIS**_ updated version in CI:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-4126/9/tests
PR landed:
https://github.com/daos-stack/daos/pull/4126

Step 2: Merge _**THIS**_ PR:
_**In-review**_
@brianjmurrell We should be able to merge this PR now, with your approval.

**Comment by brianjmurrell** [comment]
> daltonbohning force-pushed the dbohninx-update branch from cc584d8 to aaf9046 3 hours ago

@daltonbohning Just a reminder that we dis-allow force-pushing once reviewing has started on a PR.

**Review by brianjmurrell — APPROVED** [review]

**Comment by brianjmurrell** [comment]
> @brianjmurrell We should be able to merge this PR now, with your approval.

But there are going to be PRs in-flight currently that do not have daos-stack/daos#4126 merged yet.  Those will break if this lands, won't they?

**Comment by daltonbohning** [comment]
> > @brianjmurrell We should be able to merge this PR now, with your approval.
> 
> But there are going to be PRs in-flight currently that do not have [daos-stack/daos#4126](https://github.com/daos-stack/daos/pull/4126) merged yet. Those will break if this lands, won't they?

Yes, you are right. Without daos-stack/daos#4126, this updated package will cause the datamover tests to fail; though, there are no datamover tests with the `pr` tag - only `daily_regression` and `full_regression`.
What do you think is a reasonable approach?
E.g. Ask developers to rebase/merge with master ASAP. And then, `<depth-of-queue> hours` from now we land this PR?

**Comment by daltonbohning** [comment]
> > daltonbohning force-pushed the dbohninx-update branch from [cc584d8](https://github.com/daos-stack/mpifileutils-pkg/commit/cc584d8aeb3c7fb34ffdc9f0d4d818e1b22fe48e) to [aaf9046](https://github.com/daos-stack/mpifileutils-pkg/commit/aaf9046f853b08a696f0072aa6427cef69717000) 3 hours ago
> 
> @daltonbohning Just a reminder that we dis-allow force-pushing once reviewing has started on a PR.

Yes, sorry. That was for a commit that wasn't signed off.

**Comment by brianjmurrell** [comment]
> Yes, you are right. Without daos-stack/daos#4126 this updated package will cause the datamover tests to fail; though, there are no datamover tests with the `pr` tag - only `daily_regression` and `full_regression`.

Ahhh.  That saves the day then.

> What do you think is a reasonable approach?

We just need to wait until the last of the master landings that don't have daos-stack/daos#4126 in them have at least started their functional test runs and then we can land this safely.  We don't need to worry about PRs in-flight.

> E.g. Ask developers to rebase/merge with master ASAP. And then, `<depth-of-queue> hours` from now we land this PR?

That would be typical if PRs were going to be affected.  But since they won't, we don't need to do this even.  We just need to be careful not to foul up existing master runs.

I will leave it up to you to watch the queue of master builds and add the @daos-stack/release-engineering group to the reviewers of this PR when it's safe to land.  In all reality given the day and hour, that will be Monday morning at the earliest.  Which is probably the safest anyway.  #nodeployfridays

**Comment by daltonbohning** [comment]
> I will leave it up to you to watch the queue of master builds and add the @daos-stack/release-engineering group to the reviewers of this PR when it's safe to land. In all reality given the day and hour, that will be Monday morning at the earliest. Which is probably the safest anyway. #nodeployfridays

Sure! I'll check back Monday to make sure it's safe to land this PR. Thanks!

**Comment by daltonbohning** [comment]
For reference, here is the master run for  daos-stack/daos#4126. 
Previous runs have completed, and this run itself was successful. There do no appear to be any related failures.
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/master/3472/pipeline

**Pull request merged**
