### PR TITLE
DAOS-14547: update to use RO for source pool/cont

### PR DESCRIPTION
**Pull request by daltonbohning**

### CODE REVIEW

**Comment by daltonbohning** [comment]
> > @brianjmurrell There seems to be an issue with the upstream testing
> 
> Do you mean the daos testing that is done from dependency PRs? We typically call that _downstream testing_ (just so that we are all on the same nomenclature page and not confusing each other).

Yes, thanks :)

> > picking the wrong package to test.
> 
> It seems to be picking the right package to me ... which updates the commit sha to `aef784fc62b88b2a22216dd607abb2a697cd8790` as well as updates and renames the patch to `0.11.1..aef784fc62b88b2a22216dd607abb2a697cd8790.patch`

Ah! (1) I didn't realize it was changing the name based on the patch. Good to know. (2) I've been cheating and not changing the patch commit as I iterate/debug. So maybe the problem is the general repo issue of "having two packages with the exact same name"? I'll try with a proper commit and see if that helps.

Thanks for the input!

**Comment by daltonbohning** [comment]
> So maybe the problem is the general repo issue of "having two packages with the exact same name"? I'll try with a proper commit and see if that helps.

I should clarify. The reason I suspect the wrong package is because some tests are failing with an issue I already fixed and in fact verified in CI. Then when trying to fix another issue, those old issues resurfaced. Anyway, let me see if it works as expected when I push proper changes.

**Comment by daltonbohning** [comment]
Sorry for the noise here. Turns out I somehow reverted a bug fix in my mpifileutils PR :(

**Comment by daltonbohning** [comment]
Master and 2.4 testing passed: https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fmpifileutils-pkg/detail/PR-38/6/pipeline/415/

**Comment by brianjmurrell** [comment]
> Master and 2.4 testing passed: [build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fmpifileutils-pkg/detail/PR-38/6/pipeline/415](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fmpifileutils-pkg/detail/PR-38/6/pipeline/415/)

Yay, and wow.  It seems pretty rare that even downstream testing of dependencies is free of (unrelated) testing failures these days.

**Review by brianjmurrell — APPROVED** [review]

**Pull request merged**
