### PR TITLE
CORCI-1093: Update to patch 3746c05

### PR DESCRIPTION
**Pull request by daltonbohning**
CORCI-1093: Update to patch 3746c05

- Update to 3746c05
- Update packaging

Signed-off-by: Dalton Bohning <daltonx.bohning@intel.com>

### CODE REVIEW

**Comment by daltonbohning** [comment]
All datamover tests passed here: https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-5755/13/pipeline

**Comment by daltonbohning** [comment]
@brianjmurrell How should we coordinate this PR and your #14 ? This one passes all tests, so is seemingly ready to merge upon approval. But that would mean your #14 would have to rebase on this.

**Review by brianjmurrell — APPROVED** [review]

**Comment by daltonbohning** [comment]
I'm going to re-run the tests in CI on EL8 after merging this PR with the EL8 changes

**Comment by daltonbohning** [comment]
Datamover tests passed on EL7: https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-5755/13/pipeline/
Datamover tests passed on EL8: https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-5755/21/pipeline/

**Pull request merged**
